http://vnkn-bws-002.nipt.telstra.com/Group/Members/Modify/index.jsp?key=###ID###
http://vnkn-bws-002.nipt.telstra.com/User/index.jsp
http://vnkn-bws-002.nipt.telstra.com/Common/folder_contents.jsp?menuId=0
http://vnkn-bws-002.nipt.telstra.com/User/Profile
http://vnkn-bws-002.nipt.telstra.com/User/Addresses
http://vnkn-bws-002.nipt.telstra.com/User/Services
http://vnkn-bws-002.nipt.telstra.com/User/VM/General
